import { randomBytes, scrypt, timingSafeEqual } from 'node:crypto';
import { promisify } from 'node:util';
import { DB_SCHEMA, isUniqueViolation, query, transaction } from './db';
import { ROLES } from './roles';
import { ACCOUNT_STATUS, canBuyPlan } from './accountStatus';
import { isLanguage, type Language } from './languages';

const scryptAsync = promisify(scrypt) as (password: string, salt: Buffer, keylen: number) => Promise<Buffer>;

const KEY_LENGTH = 64;

export type User = {
  id: number;
  userName: string;
  emailAddress: string;
  accountStatus: string;
  signupDate: string | null;
  subscriptionEndDate: string | null;
  stripeSubscriptionId: string | null;
  // Admin or User (see ROLES)
  role: string;
  // Last picked in the Language page's "want to learn" / "I speak"
  // comboboxes; null until the user picks one
  activeLearningLanguage: Language | null;
  nativeLanguage: Language | null;
};

const USER_COLUMNS =
  'id, user_name, email_address, account_status, signup_date, subscription_end_date, stripe_subscription_id, role, active_learning_language, native_language';

// Dates are stored as ISO 8601 UTC strings, so they compare correctly as text.
// One month from `from`, clamped so Jan 31 becomes Feb 28/29 rather than Mar 3.
export function oneMonthFrom(from: Date = new Date()): string {
  const end = new Date(from);
  end.setUTCDate(1);
  end.setUTCMonth(end.getUTCMonth() + 1);
  const lastDay = new Date(Date.UTC(end.getUTCFullYear(), end.getUTCMonth() + 1, 0)).getUTCDate();
  end.setUTCDate(Math.min(from.getUTCDate(), lastDay));
  return end.toISOString();
}

export function canBuy(user: User, plan: 'monthly' | 'lifetime'): boolean {
  return canBuyPlan(user.accountStatus, plan);
}

export class EmailTakenError extends Error {
  constructor() {
    super('An account with that email address already exists');
  }
}

// Belt color for each level, indexed by level (0-8)
const BELT_COLORS = [
  'No Belt',
  'White',
  'Green',
  'Yellow',
  'Orange',
  'Blue',
  'Red',
  'Brown',
  'Black',
];

let schemaReady: Promise<void> | null = null;

export function ensureUserSchema(): Promise<void> {
  if (!schemaReady) {
    schemaReady = transaction(async (client) => {
      // Concurrent CREATE TABLE IF NOT EXISTS can still collide in Postgres
      // when several server instances boot at once, so serialize them.
      await client.query("SELECT pg_advisory_xact_lock(hashtext('talkninja_user_schema'))");
      await client.query(`CREATE SCHEMA IF NOT EXISTS ${DB_SCHEMA}`);
      // "Users" was called talkninjausers before; renaming keeps its rows and
      // everything that references it.
      await client.query(`DO $$
      BEGIN
        IF to_regclass('talkninjausers') IS NOT NULL AND to_regclass('"Users"') IS NULL THEN
          ALTER TABLE talkninjausers RENAME TO "Users";
          ALTER TABLE "Users" RENAME CONSTRAINT talkninjausers_pkey TO "Users_pkey";
          ALTER TABLE "Users" RENAME CONSTRAINT talkninjausers_role_check TO "Users_role_check";
        END IF;
      END $$`);
      // The other tables used to have snake_case names; renaming keeps their rows
      await client.query(`DO $$
      DECLARE t RECORD;
      BEGIN
        FOR t IN SELECT * FROM (VALUES
          ('belt_level_key', 'BeltLevelKey'),
          ('language_activity', 'LanguageActivity'),
          ('password_resets', 'PasswordResets'),
          ('sessions', 'Sessions'),
          ('user_language_progress', 'UserLanguageProgress')
        ) AS names (old_name, new_name)
        LOOP
          IF to_regclass(quote_ident(t.old_name)) IS NOT NULL AND to_regclass(quote_ident(t.new_name)) IS NULL THEN
            EXECUTE format('ALTER TABLE %I RENAME TO %I', t.old_name, t.new_name);
          END IF;
        END LOOP;
      END $$`);
      // Subscriptions are tracked in account_status, not role, so a role is
      // only ever Admin or User. Roles are changed by hand in the database.
      await client.query(`CREATE TABLE IF NOT EXISTS "Users" (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY,
        user_name TEXT NOT NULL,
        email_address TEXT NOT NULL,
        password TEXT NOT NULL,
        account_status TEXT NOT NULL DEFAULT '${ACCOUNT_STATUS.unsubscribed}',
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        stripe_customer_id TEXT,
        stripe_subscription_id TEXT,
        signup_date TEXT,
        subscription_end_date TEXT,
        role TEXT NOT NULL DEFAULT '${ROLES.user}',
        active_learning_language TEXT,
        native_language TEXT,
        CONSTRAINT "Users_pkey" PRIMARY KEY (id),
        CONSTRAINT "Users_role_check" CHECK (role IN ('${ROLES.admin}', '${ROLES.user}'))
      )`);
      // The belt color for each level. Seeded once; existing rows are left
      // alone so colors can be edited in the database.
      await client.query(`CREATE TABLE IF NOT EXISTS "BeltLevelKey" (
        level INTEGER PRIMARY KEY,
        belt_color TEXT NOT NULL
      )`);
      await client.query(
        `INSERT INTO "BeltLevelKey" (level, belt_color)
         SELECT * FROM unnest($1::int[], $2::text[])
         ON CONFLICT (level) DO NOTHING`,
        [BELT_COLORS.map((_, level) => level), BELT_COLORS]
      );
      // Each user's belt per language. belt_level is the highest level whose
      // Writing test they've passed (0 = No Belt); they work on the level
      // above it, one step at a time: training -> reading -> writing.
      // 'complete' means every belt has been earned.
      await client.query(`CREATE TABLE IF NOT EXISTS "UserLanguageProgress" (
        user_id INTEGER NOT NULL REFERENCES "Users"(id) ON DELETE CASCADE,
        language TEXT NOT NULL,
        belt_level INTEGER NOT NULL DEFAULT 0 REFERENCES "BeltLevelKey"(level),
        next_step TEXT NOT NULL DEFAULT 'training'
          CHECK (next_step IN ('training', 'reading', 'writing', 'complete')),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        PRIMARY KEY (user_id, language)
      )`);
      // Every completed Training and every Reading/Writing test score.
      // level is null for practice at the Fast Phrases/Words difficulties;
      // score and passed are null for Training, which isn't scored.
      // was_next_step records whether it was the user's next step (so it
      // could move them forward) rather than practice.
      await client.query(`CREATE TABLE IF NOT EXISTS "LanguageActivity" (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES "Users"(id) ON DELETE CASCADE,
        language TEXT NOT NULL,
        level INTEGER,
        activity TEXT NOT NULL CHECK (activity IN ('training', 'reading', 'writing')),
        score INTEGER CHECK (score BETWEEN 0 AND 100),
        passed BOOLEAN,
        was_next_step BOOLEAN NOT NULL,
        completed_at TIMESTAMPTZ NOT NULL DEFAULT now()
      )`);
      await client.query(
        'CREATE INDEX IF NOT EXISTS language_activity_user_language_idx ON "LanguageActivity" (user_id, language)'
      );
      // There used to be 10 levels, with Purple at 6 and Gold at 8. Each
      // level moves to its color's new level; a Purple or Gold belt becomes
      // the belt below it (Blue or Red), so no one skips a belt.
      await client.query(`DO $$
      BEGIN
        IF EXISTS (SELECT 1 FROM "BeltLevelKey" WHERE belt_color IN ('Purple', 'Gold')) THEN
          UPDATE "UserLanguageProgress"
            SET belt_level = CASE belt_level WHEN 6 THEN 5 WHEN 7 THEN 6 WHEN 8 THEN 6 WHEN 9 THEN 7 WHEN 10 THEN 8 END
            WHERE belt_level >= 6;
          UPDATE "LanguageActivity"
            SET level = CASE level WHEN 6 THEN 5 WHEN 7 THEN 6 WHEN 8 THEN 6 WHEN 9 THEN 7 WHEN 10 THEN 8 END
            WHERE level >= 6;
          DELETE FROM "BeltLevelKey" WHERE level > 8;
          UPDATE "BeltLevelKey"
            SET belt_color = CASE level WHEN 6 THEN 'Red' WHEN 7 THEN 'Brown' WHEN 8 THEN 'Black' END
            WHERE level BETWEEN 6 AND 8;
        END IF;
      END $$`);
      // Email addresses are unique regardless of case
      await client.query(
        'CREATE UNIQUE INDEX IF NOT EXISTS users_email_address_key ON "Users" (lower(email_address))'
      );
      await client.query(
        'CREATE INDEX IF NOT EXISTS users_stripe_subscription_id_idx ON "Users" (stripe_subscription_id)'
      );
      await client.query(`CREATE TABLE IF NOT EXISTS "Sessions" (
        token_hash TEXT PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES "Users"(id) ON DELETE CASCADE,
        expires_at BIGINT NOT NULL
      )`);
      await client.query('CREATE INDEX IF NOT EXISTS sessions_user_id_idx ON "Sessions" (user_id)');
      await client.query(`CREATE TABLE IF NOT EXISTS "PasswordResets" (
        token_hash TEXT PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES "Users"(id) ON DELETE CASCADE,
        expires_at BIGINT NOT NULL
      )`);
      await client.query('CREATE INDEX IF NOT EXISTS password_resets_user_id_idx ON "PasswordResets" (user_id)');
      // What a user wants their training to focus on (the Account page's
      // "Customize Training Experience"), which the word picker agent weights
      // its choices toward. No row means no custom instructions.
      await client.query(`CREATE TABLE IF NOT EXISTS "CustomAgentInstructions" (
        user_id INTEGER PRIMARY KEY REFERENCES "Users"(id) ON DELETE CASCADE,
        instructions TEXT NOT NULL,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
      )`);
      // The cancelled status used to be spelled 'Canceled'
      await client.query(`UPDATE "Users" SET account_status = $1 WHERE account_status = 'Canceled'`, [
        ACCOUNT_STATUS.canceled,
      ]);
      // Why each Monthly subscriber cancelled (the My Account page's Cancel
      // Subscription modal), one row per cancellation. The name and email are
      // copied so the row still says who it was if the account is deleted.
      // stripe_subscription_id and stripe_canceled_at are Stripe's record of
      // the cancellation; subscription_end_date is when their paid month ends.
      await client.query(`CREATE TABLE IF NOT EXISTS "CancellationReason" (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER REFERENCES "Users"(id) ON DELETE SET NULL,
        user_name TEXT NOT NULL,
        email_address TEXT NOT NULL,
        cancelled_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        reason TEXT NOT NULL,
        notes TEXT,
        stripe_subscription_id TEXT NOT NULL,
        stripe_canceled_at TIMESTAMPTZ,
        subscription_end_date TEXT
      )`);
      await client.query(
        'CREATE INDEX IF NOT EXISTS cancellation_reason_user_id_idx ON "CancellationReason" (user_id)'
      );
    }).catch((error) => {
      schemaReady = null;
      throw error;
    });
  }
  return schemaReady;
}

// Stored as "scrypt$<salt hex>$<hash hex>" so the format is self-describing.
async function hashPassword(password: string): Promise<string> {
  const salt = randomBytes(16);
  const hash = await scryptAsync(password, salt, KEY_LENGTH);
  return `scrypt$${salt.toString('hex')}$${hash.toString('hex')}`;
}

async function verifyPassword(password: string, stored: string): Promise<boolean> {
  const [scheme, saltHex, hashHex] = stored.split('$');
  if (scheme !== 'scrypt' || !saltHex || !hashHex) return false;
  const expected = Buffer.from(hashHex, 'hex');
  const actual = await scryptAsync(password, Buffer.from(saltHex, 'hex'), expected.length);
  return timingSafeEqual(actual, expected);
}

function rowToUser(row: Record<string, unknown>): User {
  return {
    id: Number(row.id),
    userName: row.user_name as string,
    emailAddress: row.email_address as string,
    accountStatus: row.account_status as string,
    role: row.role as string,
    activeLearningLanguage: isLanguage(row.active_learning_language) ? row.active_learning_language : null,
    nativeLanguage: isLanguage(row.native_language) ? row.native_language : null,
    signupDate: (row.signup_date as string | null) ?? null,
    subscriptionEndDate: (row.subscription_end_date as string | null) ?? null,
    stripeSubscriptionId: (row.stripe_subscription_id as string | null) ?? null,
  };
}

export async function createUser(input: {
  userName: string;
  emailAddress: string;
  password: string;
  // Picked on the signup page; changed later on the Account page's
  // Language Setup
  nativeLanguage: Language;
  activeLearningLanguage: Language;
}): Promise<User> {
  await ensureUserSchema();
  const passwordHash = await hashPassword(input.password);
  try {
    const rows = await query(
      `INSERT INTO "Users" (user_name, email_address, password, account_status, signup_date, role,
         native_language, active_learning_language)
       VALUES ($1, $2, $3, $6, $4, $5, $7, $8)
       RETURNING ${USER_COLUMNS}`,
      [
        input.userName,
        input.emailAddress,
        passwordHash,
        new Date().toISOString(),
        ROLES.user,
        ACCOUNT_STATUS.unsubscribed,
        input.nativeLanguage,
        input.activeLearningLanguage,
      ]
    );
    return rowToUser(rows[0]);
  } catch (error) {
    if (isUniqueViolation(error)) {
      throw new EmailTakenError();
    }
    throw error;
  }
}

// Returns the user only when the email exists and the password matches.
export async function authenticateUser(emailAddress: string, password: string): Promise<User | null> {
  await ensureUserSchema();
  const [row] = await query(
    `SELECT ${USER_COLUMNS}, password FROM "Users" WHERE lower(email_address) = lower($1)`,
    [emailAddress]
  );
  if (!row) return null;
  const ok = await verifyPassword(password, row.password as string);
  return ok ? rowToUser(row) : null;
}

export async function getUserByEmail(emailAddress: string): Promise<User | null> {
  await ensureUserSchema();
  const [row] = await query(`SELECT ${USER_COLUMNS} FROM "Users" WHERE lower(email_address) = lower($1)`, [
    emailAddress,
  ]);
  return row ? rowToUser(row) : null;
}

// Also signs the user out everywhere, since an old session may belong to
// whoever knew the previous password.
export async function updatePassword(userId: number, password: string): Promise<void> {
  await ensureUserSchema();
  const passwordHash = await hashPassword(password);
  await transaction(async (client) => {
    await client.query('UPDATE "Users" SET password = $1 WHERE id = $2', [passwordHash, userId]);
    await client.query('DELETE FROM "Sessions" WHERE user_id = $1', [userId]);
  });
}

export async function getUserById(id: number): Promise<User | null> {
  await ensureUserSchema();
  // A monthly subscription whose end date has passed (e.g. a failed renewal) is expired
  await query(
    `UPDATE "Users" SET account_status = $3
     WHERE id = $1 AND account_status = $4 AND subscription_end_date < $2`,
    [id, new Date().toISOString(), ACCOUNT_STATUS.expired, ACCOUNT_STATUS.monthly]
  );
  const [row] = await query(`SELECT ${USER_COLUMNS} FROM "Users" WHERE id = $1`, [id]);
  return row ? rowToUser(row) : null;
}

// Saves the Language page's "want to learn" and/or "I speak" picks
export async function setLanguagePreferences(
  userId: number,
  preferences: { activeLearningLanguage?: Language; nativeLanguage?: Language }
): Promise<void> {
  await ensureUserSchema();
  await query(
    `UPDATE "Users" SET active_learning_language = COALESCE($2, active_learning_language),
       native_language = COALESCE($3, native_language)
     WHERE id = $1`,
    [userId, preferences.activeLearningLanguage ?? null, preferences.nativeLanguage ?? null]
  );
}

// Links a completed Checkout Session to the user who started it.
export async function startSubscription(
  userId: number,
  stripeCustomerId: string,
  stripeSubscriptionId: string
): Promise<void> {
  await ensureUserSchema();
  await query(
    `UPDATE "Users" SET stripe_customer_id = $1, stripe_subscription_id = $2, account_status = $5,
       subscription_end_date = $3
     WHERE id = $4`,
    [stripeCustomerId, stripeSubscriptionId, oneMonthFrom(), userId, ACCOUNT_STATUS.monthly]
  );
}

// A paid Lifetime purchase never expires. Clearing the subscription ID keeps
// events from an earlier monthly subscription from changing the status.
// Returns that earlier monthly subscription's ID, if any, so the caller can
// cancel it in Stripe.
export async function grantLifetimeAccess(
  userId: number,
  stripeCustomerId: string | null
): Promise<string | null> {
  await ensureUserSchema();
  const [row] = await query(
    `UPDATE "Users" SET account_status = $3, subscription_end_date = NULL,
       stripe_subscription_id = NULL, stripe_customer_id = COALESCE($1, "Users".stripe_customer_id)
     FROM (SELECT id, stripe_subscription_id FROM "Users" WHERE id = $2) AS previous
     WHERE "Users".id = previous.id
     RETURNING previous.stripe_subscription_id AS previous_subscription_id`,
    [stripeCustomerId, userId, ACCOUNT_STATUS.lifetime]
  );
  return (row?.previous_subscription_id as string | null | undefined) ?? null;
}

// Called on each successful monthly renewal payment.
export async function renewSubscription(stripeSubscriptionId: string): Promise<void> {
  await ensureUserSchema();
  await query(
    `UPDATE "Users" SET account_status = $3, subscription_end_date = $1
     WHERE stripe_subscription_id = $2`,
    [oneMonthFrom(), stripeSubscriptionId, ACCOUNT_STATUS.monthly]
  );
}

// After Stripe has cancelled a Monthly subscription from the My Account
// page: marks the account Cancelled and saves why, together, so neither is
// saved without the other. The subscription end date is kept, since the
// month already paid for still runs to it.
export async function recordCancellation(input: {
  user: User;
  stripeSubscriptionId: string;
  stripeCanceledAt: Date | null;
  reason: string;
  notes: string | null;
}): Promise<void> {
  await ensureUserSchema();
  await transaction(async (client) => {
    await client.query('UPDATE "Users" SET account_status = $1 WHERE id = $2', [
      ACCOUNT_STATUS.canceled,
      input.user.id,
    ]);
    await client.query(
      `INSERT INTO "CancellationReason" (user_id, user_name, email_address, reason, notes,
         stripe_subscription_id, stripe_canceled_at, subscription_end_date)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8)`,
      [
        input.user.id,
        input.user.userName,
        input.user.emailAddress,
        input.reason,
        input.notes,
        input.stripeSubscriptionId,
        input.stripeCanceledAt,
        input.user.subscriptionEndDate,
      ]
    );
  });
}

export async function setStatusBySubscriptionId(
  stripeSubscriptionId: string,
  accountStatus: string
): Promise<void> {
  await ensureUserSchema();
  await query('UPDATE "Users" SET account_status = $1 WHERE stripe_subscription_id = $2', [
    accountStatus,
    stripeSubscriptionId,
  ]);
}
