import { randomBytes, scrypt, timingSafeEqual } from 'node:crypto';
import { promisify } from 'node:util';
import { isUniqueViolation, query, transaction } from './db';
import { ROLES } from './roles';
import { ACCOUNT_STATUS, canBuyPlan } from './accountStatus';
import { isLanguage, type Language } from './languages';

const scryptAsync = promisify(scrypt) as (password: string, salt: Buffer, keylen: number) => Promise<Buffer>;

const KEY_LENGTH = 64;

export type User = {
  id: number;
  userName: string;
  emailAddress: string;
  accountStatus: string;
  signupDate: string | null;
  subscriptionEndDate: string | null;
  stripeSubscriptionId: string | null;
  // Admin or User (see ROLES)
  role: string;
  // Last picked in the Language page's "want to learn" / "I speak"
  // comboboxes; null until the user picks one
  activeLearningLanguage: Language | null;
  nativeLanguage: Language | null;
};

const USER_COLUMNS =
  'id, user_name, email_address, account_status, signup_date, subscription_end_date, stripe_subscription_id, role, active_learning_language, native_language';

// Dates are stored as ISO 8601 UTC strings, so they compare correctly as text.
// One month from `from`, clamped so Jan 31 becomes Feb 28/29 rather than Mar 3.
export function oneMonthFrom(from: Date = new Date()): string {
  const end = new Date(from);
  end.setUTCDate(1);
  end.setUTCMonth(end.getUTCMonth() + 1);
  const lastDay = new Date(Date.UTC(end.getUTCFullYear(), end.getUTCMonth() + 1, 0)).getUTCDate();
  end.setUTCDate(Math.min(from.getUTCDate(), lastDay));
  return end.toISOString();
}

export function canBuy(user: User, plan: 'monthly' | 'lifetime'): boolean {
  return canBuyPlan(user.accountStatus, plan);
}

export class EmailTakenError extends Error {
  constructor() {
    super('An account with that email address already exists');
  }
}

// Belt color for each level, indexed by level (0-10)
const BELT_COLORS = [
  'No Belt',
  'White',
  'Green',
  'Yellow',
  'Orange',
  'Blue',
  'Purple',
  'Red',
  'Gold',
  'Brown',
  'Black',
];

let schemaReady: Promise<void> | null = null;

export function ensureUserSchema(): Promise<void> {
  if (!schemaReady) {
    schemaReady = transaction(async (client) => {
      // Concurrent CREATE TABLE IF NOT EXISTS can still collide in Postgres
      // when several server instances boot at once, so serialize them.
      await client.query("SELECT pg_advisory_xact_lock(hashtext('clarivex_user_schema'))");
      // TalkNinjaUsers replaced the users table. The first time it's missing
      // while users exists, copy users' structure and rows into it (ids kept,
      // so sessions, belts and activity still match). users is left untouched.
      await client.query(`DO $$
      BEGIN
        IF to_regclass('talkninjausers') IS NULL AND to_regclass('users') IS NOT NULL THEN
          CREATE TABLE talkninjausers (LIKE users INCLUDING DEFAULTS INCLUDING IDENTITY INCLUDING CONSTRAINTS);
          ALTER TABLE talkninjausers ADD PRIMARY KEY (id);
          INSERT INTO talkninjausers OVERRIDING SYSTEM VALUE SELECT * FROM users;
          PERFORM setval(pg_get_serial_sequence('talkninjausers', 'id'), coalesce(max(id), 1), max(id) IS NOT NULL)
            FROM talkninjausers;
        END IF;
      END $$`);
      await client.query(`CREATE TABLE IF NOT EXISTS talkninjausers (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_name TEXT NOT NULL,
        email_address TEXT NOT NULL,
        password TEXT NOT NULL,
        account_status TEXT NOT NULL DEFAULT '${ACCOUNT_STATUS.unsubscribed}',
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        stripe_customer_id TEXT,
        stripe_subscription_id TEXT,
        signup_date TEXT,
        subscription_end_date TEXT
      )`);
      // Users used to have first_name and last_name; now there's one
      // user_name. Older tables keep the full name ("First Last") in it.
      await client.query(`DO $$
      BEGIN
        IF EXISTS (
          SELECT 1 FROM information_schema.columns
          WHERE table_schema = current_schema() AND table_name = 'talkninjausers' AND column_name = 'first_name'
        ) THEN
          ALTER TABLE talkninjausers RENAME COLUMN first_name TO user_name;
        END IF;
        IF EXISTS (
          SELECT 1 FROM information_schema.columns
          WHERE table_schema = current_schema() AND table_name = 'talkninjausers' AND column_name = 'last_name'
        ) THEN
          UPDATE talkninjausers SET user_name = btrim(user_name || ' ' || last_name);
          ALTER TABLE talkninjausers DROP COLUMN last_name;
        END IF;
      END $$`);
      // Added after launch: when the column is first created, the site owner
      // is made Admin and everyone else is a User. After that, roles are only
      // changed by hand in the database.
      await client.query(`DO $$
      BEGIN
        IF NOT EXISTS (
          SELECT 1 FROM information_schema.columns
          WHERE table_schema = current_schema() AND table_name = 'talkninjausers' AND column_name = 'role'
        ) THEN
          ALTER TABLE talkninjausers ADD COLUMN role TEXT NOT NULL DEFAULT '${ROLES.user}';
          UPDATE talkninjausers SET role = '${ROLES.admin}' WHERE lower(email_address) = 'darinlutz@yahoo.com';
        END IF;
      END $$`);
      // Roles used to also mirror the subscription (Unsubscribed, Monthly
      // Subscriber, Lifetime Subscription); those are all Users now, and the
      // database only accepts Admin or User.
      await client.query(`ALTER TABLE talkninjausers ALTER COLUMN role SET DEFAULT '${ROLES.user}'`);
      await client.query('UPDATE talkninjausers SET role = $1 WHERE role NOT IN ($1, $2)', [ROLES.user, ROLES.admin]);
      await client.query(`DO $$
      BEGIN
        IF NOT EXISTS (
          SELECT 1 FROM pg_constraint
          WHERE conrelid = 'talkninjausers'::regclass AND conname = 'talkninjausers_role_check'
        ) THEN
          ALTER TABLE talkninjausers ADD CONSTRAINT talkninjausers_role_check
            CHECK (role IN ('${ROLES.admin}', '${ROLES.user}'));
        END IF;
      END $$`);
      // Account statuses were renamed: New -> Unsubscribed, Active -> Monthly
      // Subscription, Paid -> Lifetime Subscription. Converts any old values.
      // The Language page's "want to learn" and "I speak" picks, restored
      // when the user comes back
      await client.query('ALTER TABLE talkninjausers ADD COLUMN IF NOT EXISTS active_learning_language TEXT');
      await client.query('ALTER TABLE talkninjausers ADD COLUMN IF NOT EXISTS native_language TEXT');
      await client.query(
        `ALTER TABLE talkninjausers ALTER COLUMN account_status SET DEFAULT '${ACCOUNT_STATUS.unsubscribed}'`
      );
      await client.query(
        `UPDATE talkninjausers SET account_status = CASE account_status
           WHEN 'New' THEN $1 WHEN 'Active' THEN $2 WHEN 'Paid' THEN $3 END
         WHERE account_status IN ('New', 'Active', 'Paid')`,
        [ACCOUNT_STATUS.unsubscribed, ACCOUNT_STATUS.monthly, ACCOUNT_STATUS.lifetime]
      );
      // The belt color for each level. Seeded once; existing rows are left
      // alone so colors can be edited in the database.
      await client.query(`CREATE TABLE IF NOT EXISTS belt_level_key (
        level INTEGER PRIMARY KEY,
        belt_color TEXT NOT NULL
      )`);
      await client.query(
        `INSERT INTO belt_level_key (level, belt_color)
         SELECT * FROM unnest($1::int[], $2::text[])
         ON CONFLICT (level) DO NOTHING`,
        [BELT_COLORS.map((_, level) => level), BELT_COLORS]
      );
      // Each user's belt per language. belt_level is the highest level whose
      // Writing test they've passed (0 = No Belt); they work on the level
      // above it, one step at a time: training -> reading -> writing.
      // 'complete' means every belt has been earned.
      await client.query(`CREATE TABLE IF NOT EXISTS user_language_progress (
        user_id INTEGER NOT NULL REFERENCES talkninjausers(id) ON DELETE CASCADE,
        language TEXT NOT NULL,
        belt_level INTEGER NOT NULL DEFAULT 0 REFERENCES belt_level_key(level),
        next_step TEXT NOT NULL DEFAULT 'training'
          CHECK (next_step IN ('training', 'reading', 'writing', 'complete')),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        PRIMARY KEY (user_id, language)
      )`);
      // Every completed Training and every Reading/Writing test score.
      // level is null for practice at the Fast Phrases/Words difficulties;
      // score and passed are null for Training, which isn't scored.
      // was_next_step records whether it was the user's next step (so it
      // could move them forward) rather than practice.
      await client.query(`CREATE TABLE IF NOT EXISTS language_activity (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES talkninjausers(id) ON DELETE CASCADE,
        language TEXT NOT NULL,
        level INTEGER,
        activity TEXT NOT NULL CHECK (activity IN ('training', 'reading', 'writing')),
        score INTEGER CHECK (score BETWEEN 0 AND 100),
        passed BOOLEAN,
        was_next_step BOOLEAN NOT NULL,
        completed_at TIMESTAMPTZ NOT NULL DEFAULT now()
      )`);
      await client.query(
        'CREATE INDEX IF NOT EXISTS language_activity_user_language_idx ON language_activity (user_id, language)'
      );
      // users.level (one level, no language) predates per-language belts.
      // Those levels were Vietnamese: move them over, then drop the column.
      await client.query(`DO $$
      BEGIN
        IF EXISTS (
          SELECT 1 FROM information_schema.columns
          WHERE table_schema = current_schema() AND table_name = 'talkninjausers' AND column_name = 'level'
        ) THEN
          INSERT INTO user_language_progress (user_id, language, belt_level, next_step)
          SELECT id, 'Vietnamese', LEAST(level, 10), CASE WHEN level >= 10 THEN 'complete' ELSE 'training' END
          FROM talkninjausers WHERE level > 0
          ON CONFLICT (user_id, language) DO NOTHING;
          ALTER TABLE talkninjausers DROP COLUMN level;
        END IF;
      END $$`);
      // Email addresses are unique regardless of case
      await client.query(
        'CREATE UNIQUE INDEX IF NOT EXISTS users_email_address_key ON talkninjausers (lower(email_address))'
      );
      await client.query(
        'CREATE INDEX IF NOT EXISTS users_stripe_subscription_id_idx ON talkninjausers (stripe_subscription_id)'
      );
      await client.query(`CREATE TABLE IF NOT EXISTS sessions (
        token_hash TEXT PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES talkninjausers(id) ON DELETE CASCADE,
        expires_at BIGINT NOT NULL
      )`);
      await client.query('CREATE INDEX IF NOT EXISTS sessions_user_id_idx ON sessions (user_id)');
      await client.query(`CREATE TABLE IF NOT EXISTS password_resets (
        token_hash TEXT PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES talkninjausers(id) ON DELETE CASCADE,
        expires_at BIGINT NOT NULL
      )`);
      await client.query('CREATE INDEX IF NOT EXISTS password_resets_user_id_idx ON password_resets (user_id)');
      // Tables created while users existed still point at it: repoint them.
      await client.query(`DO $$
      DECLARE fk RECORD;
      BEGIN
        IF to_regclass('users') IS NOT NULL THEN
          FOR fk IN
            SELECT conrelid::regclass AS tbl, conname FROM pg_constraint
            WHERE contype = 'f' AND confrelid = 'users'::regclass
          LOOP
            EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I', fk.tbl, fk.conname);
            EXECUTE format('ALTER TABLE %s ADD FOREIGN KEY (user_id) REFERENCES talkninjausers(id) ON DELETE CASCADE', fk.tbl);
          END LOOP;
        END IF;
      END $$`);
    }).catch((error) => {
      schemaReady = null;
      throw error;
    });
  }
  return schemaReady;
}

// Stored as "scrypt$<salt hex>$<hash hex>" so the format is self-describing.
async function hashPassword(password: string): Promise<string> {
  const salt = randomBytes(16);
  const hash = await scryptAsync(password, salt, KEY_LENGTH);
  return `scrypt$${salt.toString('hex')}$${hash.toString('hex')}`;
}

async function verifyPassword(password: string, stored: string): Promise<boolean> {
  const [scheme, saltHex, hashHex] = stored.split('$');
  if (scheme !== 'scrypt' || !saltHex || !hashHex) return false;
  const expected = Buffer.from(hashHex, 'hex');
  const actual = await scryptAsync(password, Buffer.from(saltHex, 'hex'), expected.length);
  return timingSafeEqual(actual, expected);
}

function rowToUser(row: Record<string, unknown>): User {
  return {
    id: Number(row.id),
    userName: row.user_name as string,
    emailAddress: row.email_address as string,
    accountStatus: row.account_status as string,
    role: row.role as string,
    activeLearningLanguage: isLanguage(row.active_learning_language) ? row.active_learning_language : null,
    nativeLanguage: isLanguage(row.native_language) ? row.native_language : null,
    signupDate: (row.signup_date as string | null) ?? null,
    subscriptionEndDate: (row.subscription_end_date as string | null) ?? null,
    stripeSubscriptionId: (row.stripe_subscription_id as string | null) ?? null,
  };
}

export async function createUser(input: {
  userName: string;
  emailAddress: string;
  password: string;
}): Promise<User> {
  await ensureUserSchema();
  const passwordHash = await hashPassword(input.password);
  try {
    // New users start out as English speakers learning Spanish; they can
    // change either on the Language page
    const rows = await query(
      `INSERT INTO talkninjausers (user_name, email_address, password, account_status, signup_date, role,
         native_language, active_learning_language)
       VALUES ($1, $2, $3, $6, $4, $5, $7, $8)
       RETURNING ${USER_COLUMNS}`,
      [
        input.userName,
        input.emailAddress,
        passwordHash,
        new Date().toISOString(),
        ROLES.user,
        ACCOUNT_STATUS.unsubscribed,
        'English' satisfies Language,
        'Spanish' satisfies Language,
      ]
    );
    return rowToUser(rows[0]);
  } catch (error) {
    if (isUniqueViolation(error)) {
      throw new EmailTakenError();
    }
    throw error;
  }
}

// Returns the user only when the email exists and the password matches.
export async function authenticateUser(emailAddress: string, password: string): Promise<User | null> {
  await ensureUserSchema();
  const [row] = await query(
    `SELECT ${USER_COLUMNS}, password FROM talkninjausers WHERE lower(email_address) = lower($1)`,
    [emailAddress]
  );
  if (!row) return null;
  const ok = await verifyPassword(password, row.password as string);
  return ok ? rowToUser(row) : null;
}

export async function getUserByEmail(emailAddress: string): Promise<User | null> {
  await ensureUserSchema();
  const [row] = await query(`SELECT ${USER_COLUMNS} FROM talkninjausers WHERE lower(email_address) = lower($1)`, [
    emailAddress,
  ]);
  return row ? rowToUser(row) : null;
}

// Also signs the user out everywhere, since an old session may belong to
// whoever knew the previous password.
export async function updatePassword(userId: number, password: string): Promise<void> {
  await ensureUserSchema();
  const passwordHash = await hashPassword(password);
  await transaction(async (client) => {
    await client.query('UPDATE talkninjausers SET password = $1 WHERE id = $2', [passwordHash, userId]);
    await client.query('DELETE FROM sessions WHERE user_id = $1', [userId]);
  });
}

export async function getUserById(id: number): Promise<User | null> {
  await ensureUserSchema();
  // A monthly subscription whose end date has passed (e.g. a failed renewal) is expired
  await query(
    `UPDATE talkninjausers SET account_status = $3
     WHERE id = $1 AND account_status = $4 AND subscription_end_date < $2`,
    [id, new Date().toISOString(), ACCOUNT_STATUS.expired, ACCOUNT_STATUS.monthly]
  );
  const [row] = await query(`SELECT ${USER_COLUMNS} FROM talkninjausers WHERE id = $1`, [id]);
  return row ? rowToUser(row) : null;
}

// Saves the Language page's "want to learn" and/or "I speak" picks
export async function setLanguagePreferences(
  userId: number,
  preferences: { activeLearningLanguage?: Language; nativeLanguage?: Language }
): Promise<void> {
  await ensureUserSchema();
  await query(
    `UPDATE talkninjausers SET active_learning_language = COALESCE($2, active_learning_language),
       native_language = COALESCE($3, native_language)
     WHERE id = $1`,
    [userId, preferences.activeLearningLanguage ?? null, preferences.nativeLanguage ?? null]
  );
}

// Links a completed Checkout Session to the user who started it.
export async function startSubscription(
  userId: number,
  stripeCustomerId: string,
  stripeSubscriptionId: string
): Promise<void> {
  await ensureUserSchema();
  await query(
    `UPDATE talkninjausers SET stripe_customer_id = $1, stripe_subscription_id = $2, account_status = $5,
       subscription_end_date = $3
     WHERE id = $4`,
    [stripeCustomerId, stripeSubscriptionId, oneMonthFrom(), userId, ACCOUNT_STATUS.monthly]
  );
}

// A paid Lifetime purchase never expires. Clearing the subscription ID keeps
// events from an earlier monthly subscription from changing the status.
// Returns that earlier monthly subscription's ID, if any, so the caller can
// cancel it in Stripe.
export async function grantLifetimeAccess(
  userId: number,
  stripeCustomerId: string | null
): Promise<string | null> {
  await ensureUserSchema();
  const [row] = await query(
    `UPDATE talkninjausers SET account_status = $3, subscription_end_date = NULL,
       stripe_subscription_id = NULL, stripe_customer_id = COALESCE($1, talkninjausers.stripe_customer_id)
     FROM (SELECT id, stripe_subscription_id FROM talkninjausers WHERE id = $2) AS previous
     WHERE talkninjausers.id = previous.id
     RETURNING previous.stripe_subscription_id AS previous_subscription_id`,
    [stripeCustomerId, userId, ACCOUNT_STATUS.lifetime]
  );
  return (row?.previous_subscription_id as string | null | undefined) ?? null;
}

// Called on each successful monthly renewal payment.
export async function renewSubscription(stripeSubscriptionId: string): Promise<void> {
  await ensureUserSchema();
  await query(
    `UPDATE talkninjausers SET account_status = $3, subscription_end_date = $1
     WHERE stripe_subscription_id = $2`,
    [oneMonthFrom(), stripeSubscriptionId, ACCOUNT_STATUS.monthly]
  );
}

export async function setStatusBySubscriptionId(
  stripeSubscriptionId: string,
  accountStatus: string
): Promise<void> {
  await ensureUserSchema();
  await query('UPDATE talkninjausers SET account_status = $1 WHERE stripe_subscription_id = $2', [
    accountStatus,
    stripeSubscriptionId,
  ]);
}
